### ISSUE TITLE
This happen when player joined.

### ISSUE THREAD

**Issue by IncludivicS** [JEFF-Media-GbR/StackResize#1]
[14:41:24 ERROR]: Could not pass event InventoryClickEvent to StackResize v1.1.1
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 36
        at java.util.Arrays$ArrayList.get(Arrays.java:4165) ~[?:?]
        at net.minecraft.core.NonNullList.get(NonNullList.java:44) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.world.entity.player.Inventory.getItem(Inventory.java:615) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[paper-1.19.jar:git-Paper-14]
        at com.jeff_media.stackresize.listeners.ChangedItemMoveEventCaller.getEstimatedDestination(ChangedItemMoveEventCaller.java:95) ~[StackResize-1.1.1.jar:?]
        at com.jeff_media.stackresize.listeners.ChangedItemMoveEventCaller.onClick(ChangedItemMoveEventCaller.java:50) ~[StackResize-1.1.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor58.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-14]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:664) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3047) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1358) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1335) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1328) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1306) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[paper-1.19.jar:git-Paper-14]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-14]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:41:27 ERROR]: Could not pass event InventoryClickEvent to StackResize v1.1.1
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by mfnalex** [comment]
Thanks, fixed in 1.1.3
